query queryAudit {
  audits {
    id
    dateEnd {
      effective
      forecast
      reason
      dateUpdates {
        reason
        newDate
      }
      id
    }
    process {
      description
    }
    reportDate {
      reason
      effective
      forecast
      dateUpdates {
        newDate
        reason
      }
    }
  }
}