query MyQuery {
  noncompliances {
    actionPlan
    auditId
    createdAt
    createdBy
    deployment
    description
    evidence
    id
    modifiedAt
    modifiedBy
    priorityId
    statusId
    validation
  }
}