query queryNonCompliance {
noncompliances {
    description
    id
    priority {
      description
      id
    }
    deployment
    actionPlan
    auditId
    validation
    comments {
      comment
      createdAt
      createdBy
      id
    }
  }
}