query queryNonCompliance($auditId:[Int!]) {
  noncompliances(filters: {auditId: $auditId}) {
    description
    id
    priority {
      description
      id
    }
    identifier
    dateActionPlan {
      forecast
      id
      effective
      dateUpdates {
        id
        newDate
        reason
      }
    }
    comments {
      comment
      createdAt
      createdBy
      id
    }
    auditId
    dateDeployment {
      forecast
      id
      effective
      dateUpdates {
        id
        newDate
        reason
      }
    }
    dateValidation {
      effective
      forecast
      id
      dateUpdates {
        newDate
        id
        reason
      }
    }
    actionPlan
    deployment
    validation
    priorityId
  }
}