mutation mutationAudit($id:Int, $dateId:Int!, $processId:Int!, $reportDateId:Int) {
  putAudit(
    params: {id: $id, dateId: $dateId,  processId: $processId, reportDateId: $reportDateId}
  ) {
    id
  }
}