mutation mutationAudit($id:Int, $reportDateId:Int, $processId:Int, $dateId:Int) {
  putAudit(
    params: {id: $id, dateId: $dateId, processId: $processId, reportDateId: $reportDateId}
  ) {
    id
  }
}