mutation mutationNonCompliance ($identifier: String!, $actionPlan:Int, $auditId:Int!, $deployment:Int, $description:String!, $id:Int,  $priorityId:Int!, $validation:Int ) {
  putNoncompliance(
    params: {identifier: $identifier, actionPlan: $actionPlan, auditId: $auditId, deployment: $deployment, description: $description, id: $id, priorityId: $priorityId, validation: $validation}
  ) {
    id
  }
}